### ISSUE TITLE
Develop recommendations for visual design direction 

### ISSUE THREAD

**Issue by AvivaOskow** [18F/foia-recommendations#124]
Develop visual style direction for requester facing portal and agency-side GUI form.

Currently leaning towards basing this style off of the [US Web Design Standards](https://standards.usa.gov/) so they could be used to update the rest of FOIA.gov as well at a later date, it need be.

**Comment by AvivaOskow** [comment]
**Initial visual presentation**
https://docs.google.com/presentation/d/1fYydWjXQ2Rk0v9cjfr-3JiJ0IT0XTzc9wD5h3wgdqRg/edit#slide=id.g1c75da2867_0_99

**Style tiles**
https://docs.google.com/presentation/d/17qzyBnI__jflmAQJSfIr9SU7Zj7Aw7G6j_IFghoYOfw/edit#slide=id.g1c75da2867_0_99

**Final direction:** https://docs.google.com/presentation/d/13YUZANv-rkaAwWRs4N-74tpQ0GCUMoo8qymSFUMBzP0/edit#slide=id.g24f9d0dd68_0_40

**Comment by AvivaOskow** [comment]
![foia _style-tile_9 12 17](https://user-images.githubusercontent.com/21244661/30388796-d657269c-987e-11e7-9c62-180e2cd71804.jpg)

![foia_style-tile_r3_home_9 12 17](https://user-images.githubusercontent.com/21244661/30388801-ddd22b7e-987e-11e7-9435-9117e5f38d71.jpg)

![foia_style-tile_r3_form_9 12 17](https://user-images.githubusercontent.com/21244661/30388805-e3b92f74-987e-11e7-85d1-511484bce99b.jpg)

**Comment by adborden** [comment]
@vz3 do you want to take a look at this and close the issue if it's all :+1: ?
