### ISSUE TITLE
write research plan

### ISSUE THREAD

**Issue by leahbannon** [18F/foia-recommendations#13]
- [ ] how many interviews do we need with each type of group of users/stakeholders
- [x] what type of interviews they will be (e.g., journeymapping or something else that evolves after initial rounds of journeymapping?)
- [x] questions unique to each group
- [x] what types of interviews, synthesizing, other work needs to be done after journeymapping interviews to prepare us for design studio sketching

**Comment by vz3** [comment]
# FOIA platform research plan

This is a living document. It will be updated over the course of the coming weeks as we learn more from our users and as we hone in our hypotheses.

## Background

Initial research on National FOIA Portal. Attempting to focus on speaking to user groups who were not heavily represented in previous FOIA 1.0 research.

The goal of this research is to inform hypotheses that address the following:
- How might we create a platform that improves the FOIA requesting experience?
- How might we create a platform that increases the quality of FOIA requests?
- How might various FOIA requesters use a national FOIA platform?

## User groups

Prioritization is a function of how much insight I believe we have into a user group.

- Business/Industry (High priority)
- Attorneys (High priority)
- Medium priority (Medium priority)
- Civic society (Low priority)
- Journalists (Low priority)

### Methods

- 30-45m interviews
- Journey map: Mapping how of agencies and requesters think the process works
- Service blueprint: Neutral map documenting current process from both agency and requester perspectives.
- Usability testing (once prototype is built)
- Contextual inquiry (if time allows): Observing a FOIA requester as they file a request, follow up on existing request, and receive their responsive documents
- Diary study (if time allows): Asking a set of users to log all FOIA related activities over the lifecycle of a request.

## Interview guide

Note: Avoid detailing project scope until after the interview is complete.

### Requesters

- How often do you file FOIA requests?
- How do you decide to file a FOIA request?
- What are some things you do before filing a FOIA request?
- (If not addressed above: Do you search for existent publicly released documents before filing a FOIA request?)
- How do you identify which agency to submit your request
- How do you identify where to submit a request to an agency?
- How do you identify how to submit a request to an agency?
- Have you ever sent the same request to multiple agencies?
- How do you track the progress of your request?
- Have you experienced stalled requests? If so, what have you done in response?
- What agencies have you interacted with that you have had a particular good experience with regard to FOIA?
- Have you ever had a particularly frustrating experience with a FOIA request? (Tell us about it)
- If you could wave a magic wand to address one issue in the FOIA space, what would that issue be?

### Agency

- What percentage of your requests are:
	- duplicates?
	- not perfected?
	- directed to the wrong agency?
- How many documents do you have in your FOIA reading room?
	- How do you determine what documents will be published?
	- Are there any technical barriers to posting more documents online?
- What contributes to an increased request backlog for your agency?
- If you could wave a magic wand to address one issue in the FOIA space, what would that issue be?

**Comment by leahbannon** [comment]
Make sure these are covered:
As an agency, in order to keep up with demand fulfilling requests and avoid unnecessary work, the requests that I receive are… 
for records that my agency has
well scoped to what the requester really wants (and perfected?)
contain all the information required to fulfill the request in the law or my agency’s regulations
not for records that already exist publicly (for example, on an agency website, usa.gov, data.gov, a FOIA reading room, etc.)
As a requester, in order to easily submit a request…
I can go to one website to submit a FOIA request
my request goes to the right agency
my request is well scoped to what I want (and perfected?)
I realize before submitting my request if my information is already publicly available (for example, on an agency website, usa.gov, data.gov, a FOIA reading room, etc.)
As an agency, in order to accept/track/fulfill FOIA requests received via one central FOIA website, I can manage requests in a way that isn’t a significant burden (i.e., is interoperable with or improves my existing process).

**Comment by leahbannon** [comment]
closed via #37
