### ISSUE TITLE
[placeholder] Initial cocktail-napkin-style request form prototype

### ISSUE THREAD

**Issue by adborden** [18F/foia-recommendations#22]
As a requester, in order to submit a non-perfected FOIA request to any government agency, I need a single portal with a form where I can enter my request.

This is a first draft of what the form could look like. It doesn't need to persist any information and doesn't need to include custom fields from agencies.

- [x] A form field with contact information
- [x] A form field with request description

**Comment by leahbannon** [comment]
lgtm
