### ISSUE TITLE
populate agency and request contact information from 2015 contacts scraping data 

### ISSUE THREAD

**Issue by adborden** [18F/foia-recommendations#23]
As a requester, in order to submit my FOIA request to any of the 400+ FOIA office contacts, I need need a registry of FOIA contact information.

The contact data does not need to be up to date.

- [x] Set of form drop-downs with agency and sub-agency populated from 2015 contact data.

**Comment by pkarman** [comment]
note that I made the input field a text autocomplete with typeahead.js, and didn't have a separate field for sub-agency.

**Comment by adborden** [comment]
Yeah, I think that makes sense. It might be something we want to explicitly call out to look for in the usability tests... I could imagine typing USDA, getting a handle of offices and then not sure what to select from there. Maybe we can look back on 2015 research to get some insight there.

**Comment by pkarman** [comment]
#35 was merged. Closing this.
