### ISSUE TITLE
[discuss] draft version of a schema for a basic, minimal FOIA request

### ISSUE THREAD

**Issue by adborden** [18F/foia-recommendations#24]
As an agency, in order to talk about how systems might integrate, I need to see a draft schema of what a FOIA request might include.

For a basic, cocktail-napkin-style FOIA request.

**Comment by adborden** [comment]
Here are some fields relevant to requesters https://source.opennews.org/articles/foia-data-models/
- Agency name
- Subject/title of FOIA request
- Date filed
- Contact person—name or contact info
- Due date
- Status of request
- Date acknowledgment received
- Response tracking
- Details of request
- Who filed the request
- Reference number
- Jurisdiction (country, state, county, etc.) of agency
- Additional contact-person notes
- Misc. notes
- File name or location on drive
- Appeal info
- How requests were submitted—which medium
- Internal project name

**Comment by pkarman** [comment]
I think it's important to delineate two schemas because there are two distinct perspectives on the data: one for creating a request, and another for tracking a request. The first is a subset of the second.

## Creating a request

Based on the form at
https://foiaonline.regulations.gov/foia/action/public/request/createRequest these minimal fields are required:

* agency name
* requester name
* requester mailing address
* requester will pay up to max processing fee
* description
* fee waiver?
* expedited?

Then these additional, optional fields are present:

* requester organization
* requester email
* requester phone
* requester fax
* attachments

Written as an example SQL schema, this might look like (ignoring any normalization for things like agency, and if files or filepaths are stored in the database):

```sql
 agency_name            | character varying(255)      | not null
 requester_name         | character varying(255)      | not null
 requester_address      | text                        | not null
 max_fee                | money                       | not null default 0.00
 description            | text                        | not null
 fee_waiver             | boolean                     | not null default false
 expedited              | boolean                     | not null default false
 organization           | character varying(255)      |
 email                  | character varying(255)      |
 phone                  | character varying(255)      |
 fax                    | character varying(255)      |
 attachments            | text                        |
```

## Tracking a request

This gets into the realm of case management, for which there are many existing solutions, depending on who is doing the tracking (the requester or the agency). This is the space where things like status and timestamps and metadata *about* the request are important.

So, to extend our example from above, with the same caveats about normalization:

```sql
CREATE TYPE possible_statuses AS ENUM ('new', 'assigned', 'pending', 'closed');
CREATE TYPE possible_submission_types AS ENUM ('usps', 'fax', 'email', 'online_form');

 id                     | integer                     | not null -- internal private id
 reference_id           | uuid                        | not null -- public id
 agency_name            | character varying(255)      | not null
 requester_name         | character varying(255)      | not null
 requester_address      | text                        | not null
 max_fee                | money                       | not null default 0.00
 description            | text                        | not null
 fee_waiver             | boolean                     | not null default false
 expedited              | boolean                     | not null default false
 organization           | character varying(255)      |
 email                  | character varying(255)      |
 phone                  | character varying(255)      |
 fax                    | character varying(255)      |
 attachments            | text                        |
 status                 | possible_statuses           |
 assigned_to            | character varying(255)      |
 submitted_via          | possible_submission_types   |
 date_filed             | timestamp without time zone |
 date_due               | timestamp without time zone |
 date_acknowledged      | timestamp without time zone |
 created_at             | timestamp without time zone | not null -- about the record, not the request
 updated_at             | timestamp without time zone | not null -- about the record, not the request
```

**Comment by leahbannon** [comment]
This is the part of the law that I was thinking of, I'm not sure it matches my "napkin" concept. Let's ask DOJ about it tomorrow. Also, I'll ask if they have a list of information that's consistently always required across all agencies.

> (3)(A) Except with respect to the records made available under paragraphs (1) and (2) of this subsection, and except as provided in subparagraph (E), each agency, upon any request for records which (i) reasonably describes such records and (ii) is made in accordance with published rules stating the time, place, fees (if any), and procedures to be followed, shall make the records promptly available to any person.

**Comment by pkarman** [comment]
Here's what [FDA FOIA](https://www.fda.gov/RegulatoryInformation/FOI/HowtoMakeaFOIARequest/ucm2007229.htm)  site says:

> All FOIA requests must be in writing and should include the following information:
> A. Requestor's name, address, and telephone number.

> B. A description of the records being sought. The records should be identified as specifically as possible. A request for specific records that are releasable to the public can be processed much more quickly than a request for "all information" on a particular subject. Also fees for a more specific and limited request will generally be less.

> C. A statement concerning willingness to pay fees, including any limitations.

**Comment by adborden** [comment]
We went over this in the sprint review. The PR with this content has been merged, so I think we're all set here.
