### ISSUE TITLE
High-level blueprint for interoperability

### ISSUE THREAD

**Issue by adborden** [18F/foia-recommendations#44]
We want to demonstrate value to agencies to adopt specs and schemas.

**Comment by adborden** [comment]
@18F/foia here's the draft flow diagram, please review: https://docs.google.com/drawings/d/1ZhgDdak70S3mXHNe8Gfer0zalqHCGC506kXjD9H_tsU/edit

**Comment by pkarman** [comment]
@adborden looks good to me

**Comment by leahbannon** [comment]
First version done
