### ISSUE TITLE
synthesize research so far

### ISSUE THREAD

**Issue by leahbannon** [18F/foia-recommendations#51]

**Comment by adborden** [comment]
The research synthesis for requester interviews is all set. The highlights are pulled out in the meeting notes doc above each interview. The synthesis was published as a google doc. I think this is done, although I wonder if it's worth an artifact in Github later down the road.

**Comment by digiphile** [comment]
Are the meeting notes for each interview available? What about the synthesis?

**Comment by leahbannon** [comment]
Meeting notes, no. Synthesis, yes, coming in a couple days.

**Comment by adborden** [comment]
This is currently under review by partners :+1:
