### ISSUE TITLE
Draft of FOIA metadata (foia.xml) file

### ISSUE THREAD

**Issue by adborden** [18F/foia-recommendations#62]
Draft the kinds of fields that should exist in a FOIA metadata file. This is information that an Agency would need to publish in order for a National FOIA Platform to provide interoperability.

**Comment by pkarman** [comment]
Should we standardize on JSON like data.gov has? https://project-open-data.cio.gov/catalog/

**Comment by adborden** [comment]
Yeah, I think I would prefer JSON unless agencies already have a strong argument for XML.

**Comment by adborden** [comment]
Oh, I missied this part. It looks like JSON is required, but you can [optionally publish in additional formats](https://project-open-data.cio.gov/catalog/#implementing) as well, including RDFa Lite and XML.

**Comment by pkarman** [comment]
Some prior art examples for JSON schemas and validation:

* https://github.com/18F/e-manifest/tree/master/public/schemas
* https://github.com/18F/e-manifest/blob/master/spec/schema/post_manifest_spec.rb
* `gem 'json-schema', git: 'https://github.com/pkarman/json-schema', branch: 'require_all'`
