### ISSUE TITLE
write schema/spec feedback request

### ISSUE THREAD

**Issue by leahbannon** [18F/foia-recommendations#75]
- [x] 2-4 sentence paragraph
- [x] update flow diagram
- [x] post flow diagram on github

**Comment by adborden** [comment]
For review https://docs.google.com/drawings/d/1QaEiwV-lSdJiAEB8KhUvc4po_qCnw_CqbyCY3gp95Js/edit

**Comment by adborden** [comment]
This is the [call for feedback](https://docs.google.com/document/d/14kxg0nSX6rbKAMdc2R2iP2EfOaGPFHyPkWPWKk_aCCA/edit) I wrote the other day. It's currently shelved, but we might want to revisit it after the first round of agency feedback @pkarman is working on.
