### ISSUE TITLE
High Level Schema Suggestions

### ISSUE THREAD

**Issue by rduecyg** [18F/foia-recommendations#94]
I would recommend the schema is framed in three broad categories:

- Request submission (request, requester, agency, etc.)
- Request processing (request statuses, etc.)
- Responsive documents (file formats, file sizes, #pages, redacted y/n etc.)

**Comment by adborden** [comment]
Thanks for the recommendation, this makes a lot of sense. We've only got a [handful of schemas](https://github.com/18F/foia-recommendations/blob/master/schemas.md) for now and hadn't thought about categorizing them yet.

In terms of responsive documents, discoverability and searchability are on our radar for research but we haven't seen a need for schemas in that category.

**Comment by randomguyhere** [comment]
Could these schema be added updated to the NIEM catalogue? https://www.niem.gov

**Comment by leahbannon** [comment]
@Quietlegs we don't have budget/time for that right now, but perhaps in the next year
